basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is the back-end API for the TimeTracker application.
  title: TimeTracker Back-end API
  version: "1.0"
paths:
  /auth/login:
    post:
      description: Create or log a user
      produces:
      - text/plain
      responses:
        "200":
          description: user Exists
          schema:
            type: string
        "201":
          description: user Created
          schema:
            type: string
        "401":
          description: user not found
          schema:
            type: string
        "500":
          description: error message
          schema:
            type: string
      summary: Create or log a user
      tags:
      - auth
swagger: "2.0"
