basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is the back-end API for the TimeTracker application.
  title: TimeTracker Back-end API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Returns a "Hello, World!" string
      produces:
      - text/plain
      responses:
        "200":
          description: Success
          schema:
            type: string
      summary: Get a simple greeting
      tags:
      - Greeting
swagger: "2.0"
